spring:
  h2.console:
    enabled: true
    path: /h2-console
  r2dbc:
    url: r2dbc:h2:mem:///citydb
    username: 'sa'
    password: ''
  datasource:
    url: 'jdbc:h2:mem:citydb'
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''
